=== rmpestano/prime-arquillian/primefaces/src/main/resources-maven-jsf/misc/component.dtd
<!ELEMENT component (tag,tagClass,componentClass,componentHandlerClass?,componentType,componentFamily,rendererType?,rendererClass?,parent,description,interfaces?,attributes,resources*)>
<!ELEMENT tag (#PCDATA)>
<!ELEMENT tagClass (#PCDATA)>
<!ELEMENT componentClass (#PCDATA)>
<!ELEMENT componentHandlerClass (#PCDATA)>
<!ELEMENT componentType (#PCDATA)>
<!ELEMENT componentFamily (#PCDATA)>
<!ELEMENT rendererType (#PCDATA)>
<!ELEMENT rendererClass (#PCDATA)>
<!ELEMENT parent (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT interfaces (interface)>
<!ELEMENT interface (name)>
<!ELEMENT attributes (attribute*)>
<!ELEMENT attribute (name,required,defaultValue?,type,method-signature?,ignoreInComponent?,defaultValue?,description?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT required (#PCDATA)>
<!ELEMENT defaultValue (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT method-signature (#PCDATA)>
<!ELEMENT ignoreInComponent (#PCDATA)>
<!ELEMENT defaultValue (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT resources (resource*)>
<!ELEMENT resource (name)>

=== rmpestano/prime-arquillian/primefaces/src/main/resources-maven-jsf/mobile/rangeSlider.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY output_component_attributes			SYSTEM "../entities/output_component_attributes.xml">
<!ENTITY input_component_attributes				SYSTEM "../entities/input_component_attributes.xml">
]>
<component>
	<tag>rangeSlider</tag>
    <tagClass>org.primefaces.mobile.component.rangeslider.RangeSliderTag</tagClass>
	<componentClass>org.primefaces.mobile.component.rangeslider.RangeSlider</componentClass>
	<componentType>org.primefaces.mobile.RangeSlider</componentType>
	<componentFamily>org.primefaces.mobile.component</componentFamily>
	<rendererType>org.primefaces.mobile.component.RangeSliderRenderer</rendererType>
	<rendererClass>org.primefaces.mobile.component.rangeslider.RangeSliderRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
    <interfaces>
		<interface>
			<name>org.primefaces.component.api.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		&standard_uicomponent_attributes;
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Inline style of the container element.</description>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Style class of the container element.</description>
		</attribute>
        <attribute>
			<name>highlight</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
            <description>Highlights the value range when enabled.</description>
		</attribute>
	</attributes>
</component>

=== rmpestano/prime-arquillian/primefaces/src/main/resources-maven-jsf/mobile/field.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>field</tag>
    <tagClass>org.primefaces.mobile.component.field.FieldTag</tagClass>
	<componentClass>org.primefaces.mobile.component.field.Field</componentClass>
	<componentType>org.primefaces.mobile.Field</componentType>
	<componentFamily>org.primefaces.mobile.component</componentFamily>
	<rendererType>org.primefaces.mobile.component.FieldRenderer</rendererType>
	<rendererClass>org.primefaces.mobile.component.field.FieldRenderer</rendererClass>
	<parent>javax.faces.component.UIPanel</parent>
	<attributes>
		&standard_uicomponent_attributes;
	</attributes>
</component>

=== rmpestano/prime-arquillian/primefaces/src/main/resources-maven-jsf/mobile/header.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>header</tag>
    <tagClass>org.primefaces.mobile.component.header.HeaderTag</tagClass>
	<componentClass>org.primefaces.mobile.component.header.Header</componentClass>
	<componentType>org.primefaces.mobile.Header</componentType>
	<componentFamily>org.primefaces.mobile.component</componentFamily>
	<rendererType>org.primefaces.mobile.component.HeaderRenderer</rendererType>
	<rendererClass>org.primefaces.mobile.component.header.HeaderRenderer</rendererClass>
	<parent>javax.faces.component.UIPanel</parent>
	<attributes>
		&standard_uicomponent_attributes;
        <attribute>
			<name>title</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
        <attribute>
			<name>fixed</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
		</attribute>
        <attribute>
            <name>swatch</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Swatch of the header.</description>
        </attribute>
        <attribute>
            <name>style</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Inline style of the component.</description>
        </attribute>
        <attribute>
            <name>styleClass</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Style class of the component.</description>
        </attribute>
	</attributes>
</component>

=== rmpestano/prime-arquillian/primefaces/src/main/resources-maven-jsf/mobile/switch.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY output_component_attributes			SYSTEM "../entities/output_component_attributes.xml">
<!ENTITY input_component_attributes				SYSTEM "../entities/input_component_attributes.xml">
]>
<component>
	<tag>switch</tag>
    <tagClass>org.primefaces.mobile.component.uiswitch.UISwitchTag</tagClass>
	<componentClass>org.primefaces.mobile.component.uiswitch.UISwitch</componentClass>
	<componentType>org.primefaces.mobile.UISwitch</componentType>
	<componentFamily>org.primefaces.mobile.component</componentFamily>
	<rendererType>org.primefaces.mobile.component.UISwitchRenderer</rendererType>
	<rendererClass>org.primefaces.mobile.component.uiswitch.UISwitchRenderer</rendererClass>
	<parent>javax.faces.component.UIInput</parent>
    <interfaces>
		<interface>
			<name>org.primefaces.component.api.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		&input_component_attributes;
        <attribute>
            <name>onLabel</name>
            <required>false</required>
            <type>java.lang.String</type>
            <defaultValue>on</defaultValue>
            <description>Custom label for on state.</description>
        </attribute>
        <attribute>
            <name>offLabel</name>
            <required>false</required>
            <type>java.lang.String</type>
            <defaultValue>off</defaultValue>
            <description>Custom label for off state.</description>
        </attribute>
        <attribute>
			<name>label</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>User presentable name.</description>
		</attribute>
        <attribute>
			<name>disabled</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
            <description>Disables or enables the switch.</description>
		</attribute>
        <attribute>
            <name>onchange</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Client side callback to execute on value change event.</description>
        </attribute>
        <attribute>
            <name>style</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Inline style of the main container.</description>
        </attribute>
        <attribute>
            <name>styleClass</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Style class of the main container.</description>
        </attribute>
	</attributes>
</component>

=== rmpestano/prime-arquillian/primefaces/src/main/resources-maven-jsf/ui/bubbleChart.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
    <tag>bubbleChart</tag>
    <tagClass>org.primefaces.component.chart.bubble.BubbleChartTag</tagClass>
    <componentClass>org.primefaces.component.chart.bubble.BubbleChart</componentClass>
    <componentType>org.primefaces.component.chart.BubbleChart</componentType>
    <componentFamily>org.primefaces.component</componentFamily>
    <rendererType>org.primefaces.component.chart.BubbleChartRenderer</rendererType>
    <rendererClass>org.primefaces.component.chart.bubble.BubbleChartRenderer</rendererClass>
    <parent>org.primefaces.component.chart.UIChart</parent>
    <interfaces>
        <interface>
            <name>org.primefaces.component.api.Widget</name>
        </interface>
    </interfaces>
    <attributes>
		&standard_uicomponent_attributes;
		&widget_var_attribute;
        <attribute>
            <name>value</name>
            <required>false</required>
            <type>org.primefaces.model.chart.BubbleChartModel</type>
        </attribute>
        <attribute>
            <name>style</name>
            <required>false</required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>styleClass</name>
            <required>false</required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>title</name>
            <required>false</required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>shadow</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>seriesColors</name>
            <required>false</required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>bubbleGradients</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
        </attribute>
        <attribute>
            <name>bubbleAlpha</name>
            <required>false</required>
            <type>java.lang.Double</type>
            <defaultValue>1.0</defaultValue>
        </attribute>
        <attribute>
            <name>showLabels</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
        </attribute>
        <attribute>
            <name>xaxisLabel</name>
            <required>false</required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>yaxisLabel</name>
            <required>false</required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>xaxisAngle</name>
            <required>false</required>
            <type>java.lang.Integer</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>yaxisAngle</name>
            <required>false</required>
            <type>java.lang.Integer</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
			<name>zoom</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Enables plot zooming.</description>
		</attribute>
        <attribute>
			<name>extender</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Javascript function to extend the chart with low level jqplot options.</description>
            <ignoreInComponent>true</ignoreInComponent>
		</attribute>
        <attribute>
			<name>showDatatip</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
            <description>Defines visibility of datatip, default is true.</description>
		</attribute>
        <attribute>
			<name>datatipFormat</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Template string for datatips.</description>
		</attribute>
    </attributes>
	<resources>
        <resource>
			<name>charts/charts.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>primefaces.js</name>
		</resource>
		<resource>
			<name>charts/charts.js</name>
		</resource>
	</resources>
</component>

=== rmpestano/prime-arquillian/primefaces/src/main/resources-maven-jsf/mobile/content.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>content</tag>
    <tagClass>org.primefaces.mobile.component.content.ContentTag</tagClass>
	<componentClass>org.primefaces.mobile.component.content.Content</componentClass>
	<componentType>org.primefaces.mobile.Content</componentType>
	<componentFamily>org.primefaces.mobile.component</componentFamily>
	<rendererType>org.primefaces.mobile.component.ContentRenderer</rendererType>
	<rendererClass>org.primefaces.mobile.component.content.ContentRenderer</rendererClass>
	<parent>javax.faces.component.UIPanel</parent>
	<attributes>
		&standard_uicomponent_attributes;
        <attribute>
            <name>style</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Inline style of the component.</description>
        </attribute>
        <attribute>
            <name>styleClass</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Style class of the component.</description>
        </attribute>
	</attributes>
</component>
