=== rmpestano/prime-arquillian/primefaces/src/main/resources-maven-jsf/misc/component.dtd
<!ELEMENT component (tag,tagClass,componentClass,componentHandlerClass?,componentType,componentFamily,rendererType?,rendererClass?,parent,description,interfaces?,attributes,resources*)>
<!ELEMENT tag (#PCDATA)>
<!ELEMENT tagClass (#PCDATA)>
<!ELEMENT componentClass (#PCDATA)>
<!ELEMENT componentHandlerClass (#PCDATA)>
<!ELEMENT componentType (#PCDATA)>
<!ELEMENT componentFamily (#PCDATA)>
<!ELEMENT rendererType (#PCDATA)>
<!ELEMENT rendererClass (#PCDATA)>
<!ELEMENT parent (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT interfaces (interface)>
<!ELEMENT interface (name)>
<!ELEMENT attributes (attribute*)>
<!ELEMENT attribute (name,required,defaultValue?,type,method-signature?,ignoreInComponent?,defaultValue?,description?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT required (#PCDATA)>
<!ELEMENT defaultValue (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT method-signature (#PCDATA)>
<!ELEMENT ignoreInComponent (#PCDATA)>
<!ELEMENT defaultValue (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT resources (resource*)>
<!ELEMENT resource (name)>

=== rmpestano/prime-arquillian/primefaces/src/main/resources-maven-jsf/ui/autoComplete.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY output_component_attributes			SYSTEM "../entities/output_component_attributes.xml">
<!ENTITY input_component_attributes				SYSTEM "../entities/input_component_attributes.xml">
<!ENTITY html_input_text_attributes				SYSTEM "../entities/html_input_text_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
    <tag>autoComplete</tag>
    <tagClass>org.primefaces.component.autocomplete.AutoCompleteTag</tagClass>
    <componentHandlerClass>org.primefaces.component.autocomplete.AutoCompleteHandler</componentHandlerClass>
    <componentClass>org.primefaces.component.autocomplete.AutoComplete</componentClass>
    <componentType>org.primefaces.component.AutoComplete</componentType>
    <componentFamily>org.primefaces.component</componentFamily>
    <rendererType>org.primefaces.component.AutoCompleteRenderer</rendererType>
    <rendererClass>org.primefaces.component.autocomplete.AutoCompleteRenderer</rendererClass>
    <parent>javax.faces.component.html.HtmlInputText</parent>
    <description>AutoComplete provides live suggestions while an input is being typed.</description>
    <interfaces>
		<interface>
			<name>org.primefaces.component.api.Widget</name>
		</interface>
        <interface>
			<name>org.primefaces.component.api.InputHolder</name>
		</interface>
        <interface>
			<name>org.primefaces.component.api.MixedClientBehaviorHolder</name>
		</interface>
	</interfaces>
    <attributes>
        &input_component_attributes;
        &html_input_text_attributes;
        &widget_var_attribute;
        <attribute>
            <name>completeMethod</name>
            <required>false</required>
            <type>javax.el.MethodExpression</type>
            <method-signature>java.util.List completeMethod(java.lang.String)</method-signature>
            <description>Method providing suggestions.</description>
        </attribute>
        <attribute>
            <name>var</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Name of the iterator used in pojo based suggestion.</description>
        </attribute>
        <attribute>
            <name>itemLabel</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Label of the item.</description>
        </attribute>
        <attribute>
            <name>itemValue</name>
            <required>false</required>
            <type>java.lang.Object</type>
            <description>Value of the item.</description>
        </attribute>
        <attribute>
            <name>maxResults</name>
            <required>false</required>
            <type>java.lang.Integer</type>
            <defaultValue>java.lang.Integer.MAX_VALUE</defaultValue>
            <description>Maximum number of results to be displayed. Default is unlimited.</description>
        </attribute>
        <attribute>
            <name>minQueryLength</name>
            <required>false</required>
            <type>java.lang.Integer</type>
            <defaultValue>1</defaultValue>
            <description>Number of characters to be typed before starting to query. Default is 1.</description>
        </attribute>
        <attribute>
            <name>queryDelay</name>
            <required>false</required>
            <type>java.lang.Integer</type>
            <defaultValue>300</defaultValue>
            <description>Delay to wait in milliseconds before sending each query to the server. Default is 300.</description>
        </attribute>
        <attribute>
            <name>queryDeletionDelay</name>
            <required>false</required>
            <type>java.lang.Integer</type>
            <defaultValue>600</defaultValue>
            <description>Delay to wait in milliseconds, after deleting a character and before sending each query to the server Default is 600.</description>
        </attribute>
        <attribute>
            <name>forceSelection</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>When enabled, autoComplete only accepts input from the selection list. Default is false.</description>
        </attribute>
        <attribute>
            <name>scrollHeight</name>
            <required>false</required>
            <type>java.lang.Integer</type>
            <defaultValue>java.lang.Integer.MAX_VALUE</defaultValue>
            <description>Defines the height of the viewport for autocomplete suggestions.</description>
        </attribute>
        <attribute>
            <name>effect</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>effectDuration</name>
            <required>false</required>
            <type>java.lang.Integer</type>
            <defaultValue>400</defaultValue>
        </attribute>
        <attribute>
            <name>dropdown</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
        </attribute>
        <attribute>
            <name>panelStyle</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>panelStyleClass</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>multiple</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
        </attribute>
        <attribute>
            <name>itemtipMyPosition</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Position of itemtip with respect to item. Default is "left top".</description>
        </attribute>
        <attribute>
            <name>itemtipAtPosition</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Position of item with respect to item. Default is "right bottom".</description>
        </attribute>
        <attribute>
            <name>cache</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>When enabled autocomplete caches the searched result list.</description>
        </attribute>
        <attribute>
            <name>cacheTimeout</name>
            <required>false</required>
            <type>java.lang.Integer</type>
            <defaultValue>300000</defaultValue>
            <description>Timeout value for cached results.</description>
        </attribute>
        <attribute>
            <name>emptyMessage</name>
            <required>false</required>
            <type>java.lang.String</type>
            <defaultValue></defaultValue>
            <description>Text to display when there is no data to display.</description>
        </attribute>
        <attribute>
            <name>appendTo</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Appends the overlay to the element defined by search expression. Defaults to document body.</description>
        </attribute>
    </attributes>
    <resources>
        <resource>
			<name>primefaces.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
        <resource>
			<name>jquery/jquery-plugins.js</name>
		</resource>
        <resource>
			<name>primefaces.js</name>
		</resource>
    </resources>
</component>

=== rmpestano/prime-arquillian/primefaces/src/main/resources-maven-jsf/ui/donutChart.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
    <tag>donutChart</tag>
    <tagClass>org.primefaces.component.chart.donut.DonutChartTag</tagClass>
    <componentClass>org.primefaces.component.chart.donut.DonutChart</componentClass>
    <componentType>org.primefaces.component.chart.DonutChart</componentType>
    <componentFamily>org.primefaces.component</componentFamily>
    <rendererType>org.primefaces.component.chart.DonutChartRenderer</rendererType>
    <rendererClass>org.primefaces.component.chart.donut.DonutChartRenderer</rendererClass>
    <parent>org.primefaces.component.chart.UIChart</parent>
    <interfaces>
        <interface>
            <name>org.primefaces.component.api.Widget</name>
        </interface>
    </interfaces>
    <attributes>
		&standard_uicomponent_attributes;
		&widget_var_attribute;
        <attribute>
            <name>value</name>
            <required>false</required>
            <type>org.primefaces.model.chart.DonutChartModel</type>
        </attribute>
        <attribute>
            <name>style</name>
            <required>false</required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>styleClass</name>
            <required>false</required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>title</name>
            <required>false</required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>legendPosition</name>
            <required>false</required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>seriesColors</name>
            <required>false</required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>sliceMargin</name>
            <required>false</required>
            <type>java.lang.Integer</type>
            <defaultValue>0</defaultValue>
        </attribute>
        <attribute>
            <name>fill</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
        </attribute>
        <attribute>
            <name>shadow</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>showDataLabels</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Whether data information will be showed on chart. Default is false.</description>
        </attribute>
        <attribute>
            <name>dataFormat</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Defines data information type on highlighter or slices. Default is percent.</description>
        </attribute>
        <attribute>
			<name>legendCols</name>
			<required>false</required>
			<type>java.lang.Integer</type>
            <description>Defines visible column count of chart legend.</description>
            <ignoreInComponent>true</ignoreInComponent>
		</attribute>
        <attribute>
			<name>legendRows</name>
			<required>false</required>
			<type>java.lang.Integer</type>
            <description>Defines visible row count of chart legend.</description>
            <ignoreInComponent>true</ignoreInComponent>
		</attribute>
        <attribute>
			<name>extender</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Javascript function to extend the chart with low level jqplot options.</description>
            <ignoreInComponent>true</ignoreInComponent>
		</attribute>
    </attributes>
	<resources>
        <resource>
			<name>charts/charts.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>primefaces.js</name>
		</resource>
		<resource>
			<name>charts/charts.js</name>
		</resource>
	</resources>
</component>

=== rmpestano/prime-arquillian/primefaces/src/main/resources-maven-jsf/ui/barChart.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>barChart</tag>
	<tagClass>org.primefaces.component.chart.bar.BarChartTag</tagClass>
	<componentClass>org.primefaces.component.chart.bar.BarChart</componentClass>
	<componentType>org.primefaces.component.chart.BarChart</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.chart.BarChartRenderer</rendererType>
	<rendererClass>org.primefaces.component.chart.bar.BarChartRenderer</rendererClass>
	<parent>org.primefaces.component.chart.CartesianChart</parent>
    <interfaces>
		<interface>
			<name>org.primefaces.component.api.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		&standard_uicomponent_attributes;
		&widget_var_attribute;
		<attribute>
			<name>value</name>
			<required>false</required>
			<type>org.primefaces.model.chart.CartesianChartModel</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
        <attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
        <attribute>
			<name>title</name>
			<required>false</required>
			<type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
		</attribute>
        <attribute>
			<name>legendPosition</name>
			<required>false</required>
			<type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
		</attribute>
        <attribute>
			<name>barPadding</name>
			<required>false</required>
			<type>java.lang.Integer</type>
            <defaultValue>8</defaultValue>
		</attribute>
        <attribute>
			<name>barMargin</name>
			<required>false</required>
			<type>java.lang.Integer</type>
            <defaultValue>10</defaultValue>
		</attribute>
        <attribute>
			<name>orientation</name>
			<required>false</required>
			<type>java.lang.String</type>
            <defaultValue>vertical</defaultValue>
		</attribute>
        <attribute>
			<name>stacked</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
		</attribute>
        <attribute>
			<name>min</name>
			<required>false</required>
			<type>java.lang.Double</type>
			<defaultValue>java.lang.Double.MIN_VALUE</defaultValue>
		</attribute>
		<attribute>
			<name>max</name>
			<required>false</required>
			<type>java.lang.Double</type>
			<defaultValue>java.lang.Double.MAX_VALUE</defaultValue>
		</attribute>
        <attribute>
			<name>breakOnNull</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
		</attribute>
        <attribute>
			<name>seriesColors</name>
			<required>false</required>
			<type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
		</attribute>
        <attribute>
			<name>shadow</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <ignoreInComponent>true</ignoreInComponent>
		</attribute>
        <attribute>
			<name>xaxisLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
        <ignoreInComponent>true</ignoreInComponent>
		</attribute>
        <attribute>
			<name>yaxisLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
        <ignoreInComponent>true</ignoreInComponent>
		</attribute>
        <attribute>
			<name>xaxisAngle</name>
			<required>false</required>
			<type>java.lang.Integer</type>
        <ignoreInComponent>true</ignoreInComponent>
		</attribute>
        <attribute>
			<name>yaxisAngle</name>
			<required>false</required>
			<type>java.lang.Integer</type>
            <ignoreInComponent>true</ignoreInComponent>
		</attribute>
        <attribute>
			<name>legendCols</name>
			<required>false</required>
			<type>java.lang.Integer</type>
            <description>Defines visible column count of chart legend.</description>
            <ignoreInComponent>true</ignoreInComponent>
		</attribute>
        <attribute>
			<name>legendRows</name>
			<required>false</required>
			<type>java.lang.Integer</type>
            <description>Defines visible row count of chart legend.</description>
            <ignoreInComponent>true</ignoreInComponent>
		</attribute>
        <attribute>
			<name>zoom</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Enables plot zooming.</description>
		</attribute>
        <attribute>
			<name>extender</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Javascript function to extend the chart with low level jqplot options.</description>
            <ignoreInComponent>true</ignoreInComponent>
		</attribute>
        <attribute>
			<name>animate</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Enables animation on plot, default is false.</description>
		</attribute>
        <attribute>
			<name>showDatatip</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
            <description>Defines visibility of datatip, default is true.</description>
		</attribute>
        <attribute>
			<name>datatipFormat</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Template string for datatips.</description>
		</attribute>
	</attributes>
	<resources>
        <resource>
			<name>charts/charts.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>primefaces.js</name>
		</resource>
		<resource>
			<name>charts/charts.js</name>
		</resource>
	</resources>
</component>

=== rmpestano/prime-arquillian/primefaces/src/main/resources-maven-jsf/ui/photocam.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY output_component_attributes			SYSTEM "../entities/output_component_attributes.xml">
<!ENTITY input_component_attributes				SYSTEM "../entities/input_component_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>photoCam</tag>
	<tagClass>org.primefaces.component.photocam.PhotoCamTag</tagClass>
    <componentHandlerClass>org.primefaces.component.photocam.PhotoCamHandler</componentHandlerClass>
	<componentClass>org.primefaces.component.photocam.PhotoCam</componentClass>
	<componentType>org.primefaces.component.PhotoCam</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.PhotoCamRenderer</rendererType>
	<rendererClass>org.primefaces.component.photocam.PhotoCamRenderer</rendererClass>
	<parent>javax.faces.component.UIInput</parent>
    <description>.</description>
    <interfaces>
		<interface>
			<name>org.primefaces.component.api.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		&input_component_attributes;
        &widget_var_attribute;
		<attribute>
            <name>style</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Style of the camera container.</description>
        </attribute>
        <attribute>
            <name>styleClass</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Style class of the camera container.</description>
        </attribute>
        <attribute>
            <name>process</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Identifiers of components to process during photo capture.</description>
        </attribute>
        <attribute>
            <name>update</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Identifiers of components to update after photo capture.</description>
        </attribute>
        <attribute>
			<name>listener</name>
			<required>false</required>
			<type>javax.el.MethodExpression</type>
			<method-signature>void listener(org.primefaces.event.CaptureEvent)</method-signature>
            <description>Method expression to listen capture events.</description>
		</attribute>
	</attributes>
    <resources>
        <resource>
            <name>primefaces.css</name>
        </resource>
        <resource>
            <name>jquery/jquery.js</name>
        </resource>
        <resource>
            <name>primefaces.js</name>
        </resource>
        <resource>
            <name>photocam/photocam.js</name>
        </resource>
	</resources>
</component>

=== rmpestano/prime-arquillian/primefaces/src/main/resources-maven-jsf/ui/outputPanel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
]>
<component>
	<tag>outputPanel</tag>
	<tagClass>org.primefaces.component.outputpanel.OutputPanelTag</tagClass>
	<componentClass>org.primefaces.component.outputpanel.OutputPanel</componentClass>
	<componentType>org.primefaces.component.OutputPanel</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.OutputPanelRenderer</rendererType>
	<rendererClass>org.primefaces.component.outputpanel.OutputPanelRenderer</rendererClass>
	<parent>javax.faces.component.UIPanel</parent>
    <description>OutputPanel is used to group content on a page.</description>
    <interfaces>
        <interface>
			<name>org.primefaces.component.api.Widget</name>
		</interface>
		<interface>
			<name>org.primefaces.component.api.AutoUpdatable</name>
		</interface>
	</interfaces>
    <attributes>
		&standard_uicomponent_attributes;
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Style of the html container element.</description>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>StyleClass of the html container element.</description>
		</attribute>
        <attribute>
			<name>autoUpdate</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Updates outputPanel after each ajax request implicity.</description>
		</attribute>
        <attribute>
			<name>deferred</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Deferred mode loads the contents after page load to speed up page load.</description>
		</attribute>
        <attribute>
			<name>deferredMode</name>
			<required>false</required>
			<type>java.lang.String</type>
            <defaultValue>load</defaultValue>
            <description>Defines deferred loading mode, valid values are "load" (after page load) and "visible" (once the panel is visible on scroll). Default value is "load".</description>
		</attribute>
        <attribute>
            <name>global</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Global ajax requests are listened by ajaxStatus component, setting global to false will not trigger ajaxStatus on deferred loading. Default is false.</description>
        </attribute>
        <attribute>
            <name>layout</name>
            <required>false</required>
            <type>java.lang.String</type>
            <defaultValue>block</defaultValue>
            <description>Shortcut for the css display property, valid values are block (default) and inline.</description>
        </attribute>
	</attributes>
    <resources>
		<resource>
			<name>primefaces.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>primefaces.js</name>
		</resource>
	</resources>
</component>

=== rmpestano/prime-arquillian/primefaces/src/main/resources-maven-jsf/mobile/page.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>page</tag>
    <tagClass>org.primefaces.mobile.component.page.PageTag</tagClass>
	<componentClass>org.primefaces.mobile.component.page.Page</componentClass>
	<componentType>org.primefaces.mobile.Page</componentType>
	<componentFamily>org.primefaces.mobile.component</componentFamily>
	<rendererType>org.primefaces.mobile.component.PageRenderer</rendererType>
	<rendererClass>org.primefaces.mobile.component.page.PageRenderer</rendererClass>
	<parent>javax.faces.component.UIPanel</parent>
	<attributes>
		&standard_uicomponent_attributes;
        <attribute>
            <name>title</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Title of the view.</description>
        </attribute>
        <attribute>
            <name>theme</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Theme of the view.</description>
        </attribute>
        <attribute>
            <name>style</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Inline style of the component.</description>
        </attribute>
        <attribute>
            <name>styleClass</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Style class of the component.</description>
        </attribute>
        <attribute>
            <name>lazy</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Lazy loading views are not rendered on initial page load to improve performance and instead lazily loaded on demand when there are first navigated to.</description>
        </attribute>
	</attributes>
</component>
