=== rmpestano/prime-arquillian/primefaces/src/main/resources-maven-jsf/misc/component.dtd
<!ELEMENT component (tag,tagClass,componentClass,componentHandlerClass?,componentType,componentFamily,rendererType?,rendererClass?,parent,description,interfaces?,attributes,resources*)>
<!ELEMENT tag (#PCDATA)>
<!ELEMENT tagClass (#PCDATA)>
<!ELEMENT componentClass (#PCDATA)>
<!ELEMENT componentHandlerClass (#PCDATA)>
<!ELEMENT componentType (#PCDATA)>
<!ELEMENT componentFamily (#PCDATA)>
<!ELEMENT rendererType (#PCDATA)>
<!ELEMENT rendererClass (#PCDATA)>
<!ELEMENT parent (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT interfaces (interface)>
<!ELEMENT interface (name)>
<!ELEMENT attributes (attribute*)>
<!ELEMENT attribute (name,required,defaultValue?,type,method-signature?,ignoreInComponent?,defaultValue?,description?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT required (#PCDATA)>
<!ELEMENT defaultValue (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT method-signature (#PCDATA)>
<!ELEMENT ignoreInComponent (#PCDATA)>
<!ELEMENT defaultValue (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT resources (resource*)>
<!ELEMENT resource (name)>

=== rmpestano/prime-arquillian/primefaces/src/main/resources-maven-jsf/ui/tooltip.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
<!ENTITY output_component_attributes			SYSTEM "../entities/output_component_attributes.xml">
]>
<component>
	<tag>tooltip</tag>
	<tagClass>org.primefaces.component.tooltip.TooltipTag</tagClass>
	<componentClass>org.primefaces.component.tooltip.Tooltip</componentClass>
	<componentType>org.primefaces.component.Tooltip</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.TooltipRenderer</rendererType>
	<rendererClass>org.primefaces.component.tooltip.TooltipRenderer</rendererClass>
	<parent>javax.faces.component.UIOutput</parent>
    <description>Tooltip goes beyond the legacy html title attribute by providing custom effects, events, html content and advance theme support.</description>
     <interfaces>
		<interface>
			<name>org.primefaces.component.api.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		&output_component_attributes;
		&widget_var_attribute;
		<attribute>
			<name>showEvent</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Event displaying the tooltip. Default is mouseover.</description>
		</attribute>
		<attribute>
			<name>showEffect</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>fade</defaultValue>
            <description>Effect to be used for displaying. Default is fade.</description>
		</attribute>
        <attribute>
			<name>showDelay</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>150</defaultValue>
            <description>Delay time to show tooltip in milliseconds. Default is 150.</description>
		</attribute>
		<attribute>
			<name>hideEvent</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Event hiding the tooltip. Default is mouseout.</description>
		</attribute>
		<attribute>
			<name>hideEffect</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>fade</defaultValue>
            <description>Effect to be used for hiding. Default is fade.</description>
		</attribute>
        <attribute>
			<name>hideDelay</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>0</defaultValue>
            <description>Delay time to hide tooltip in milliseconds. Default is 0</description>
		</attribute>
		<attribute>
			<name>for</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Id of the component to attach the tooltip.</description>
		</attribute>
        <attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Inline style of the tooltip.</description>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Style class of the tooltip.</description>
		</attribute>
        <attribute>
			<name>globalSelector</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>jquery selector for global tooltip, default is "a,:input,:button".</description>
		</attribute>
        <attribute>
			<name>escape</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
            <description>Defines whether html would be escaped or not, defaults to true.</description>
		</attribute>
        <attribute>
			<name>trackMouse</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Tooltip position follows pointer on mousemove, default is false</description>
		</attribute>
	</attributes>
    <resources>
        <resource>
			<name>primefaces.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
        <resource>
			<name>jquery/jquery-plugins.js</name>
		</resource>
        <resource>
			<name>primefaces.js</name>
		</resource>
	</resources>
</component>

=== rmpestano/prime-arquillian/primefaces/src/main/resources-maven-jsf/ui/ring.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY data_component_attributes				SYSTEM "../entities/data_component_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>ring</tag>
	<tagClass>org.primefaces.component.ring.RingTag</tagClass>
	<componentClass>org.primefaces.component.ring.Ring</componentClass>
	<componentType>org.primefaces.component.Ring</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.RingRenderer</rendererType>
	<rendererClass>org.primefaces.component.ring.RingRenderer</rendererClass>
	<parent>org.primefaces.component.api.UIData</parent>
    <interfaces>
		<interface>
			<name>org.primefaces.component.api.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		&data_component_attributes;
		&widget_var_attribute;
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
        <attribute>
			<name>easing</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>ring/ring.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>primefaces.js</name>
		</resource>
		<resource>
			<name>ring/ring.js</name>
		</resource>
	</resources>
</component>

=== rmpestano/prime-arquillian/primefaces/src/main/resources-maven-jsf/ui/selectBooleanButton.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY output_component_attributes			SYSTEM "../entities/output_component_attributes.xml">
<!ENTITY input_component_attributes				SYSTEM "../entities/input_component_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>selectBooleanButton</tag>
	<tagClass>org.primefaces.component.selectbooleanbutton.SelectBooleanButtonTag</tagClass>
	<componentClass>org.primefaces.component.selectbooleanbutton.SelectBooleanButton</componentClass>
	<componentType>org.primefaces.component.SelectBooleanButton</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.SelectBooleanButtonRenderer</rendererType>
	<rendererClass>org.primefaces.component.selectbooleanbutton.SelectBooleanButtonRenderer</rendererClass>
	<parent>javax.faces.component.html.HtmlSelectBooleanCheckbox</parent>
    <interfaces>
		<interface>
			<name>org.primefaces.component.api.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		&input_component_attributes;
        &widget_var_attribute;
        <attribute>
            <name>disabled</name>
            <required>false</required>
            <type>boolean</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>label</name>
            <required>false</required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>onchange</name>
            <required>false</required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>style</name>
            <required>false</required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>styleClass</name>
            <required>false</required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>onLabel</name>
            <required>true</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>offLabel</name>
            <required>true</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>onIcon</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>offIcon</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
	</attributes>
    <resources>
        <resource>
			<name>primefaces.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
        <resource>
			<name>primefaces.js</name>
		</resource>
	</resources>
</component>

=== rmpestano/prime-arquillian/primefaces/src/main/resources-maven-jsf/ui/captcha.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY output_component_attributes			SYSTEM "../entities/output_component_attributes.xml">
<!ENTITY input_component_attributes				SYSTEM "../entities/input_component_attributes.xml">
]>
<component>
	<tag>captcha</tag>
	<tagClass>org.primefaces.component.captcha.CaptchaTag</tagClass>
	<componentClass>org.primefaces.component.captcha.Captcha</componentClass>
	<componentType>org.primefaces.component.Captcha</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.CaptchaRenderer</rendererType>
	<rendererClass>org.primefaces.component.captcha.CaptchaRenderer</rendererClass>
	<parent>javax.faces.component.UIInput</parent>
    <description>Captcha is a form validation component based on Recaptcha API.</description>
	<attributes>
		&input_component_attributes;
		<attribute>
			<name>theme</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>red</defaultValue>
            <description>Theme of the captcha. Default is red.</description>
		</attribute>
		<attribute>
			<name>language</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>en</defaultValue>
            <description>Key of the supported languages. Default is "en".</description>
		</attribute>
		<attribute>
			<name>tabindex</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>0</defaultValue>
            <description>Position of the input element in the tabbing order.</description>
		</attribute>
        <attribute>
			<name>label</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>A localized user presentable name.</description>
		</attribute>
        <attribute>
			<name>secure</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Enables https support.</description>
		</attribute>
	</attributes>
</component>

=== rmpestano/prime-arquillian/primefaces/src/main/resources-maven-jsf/ui/ajaxExceptionHandler.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
    <tag>ajaxExceptionHandler</tag>
    <tagClass>org.primefaces.component.ajaxexceptionhandler.AjaxExceptionHandler</tagClass>
    <componentClass>org.primefaces.component.ajaxexceptionhandler.AjaxExceptionHandler</componentClass>
    <componentType>org.primefaces.component.AjaxExceptionHandler</componentType>
    <componentFamily>org.primefaces.component</componentFamily>
    <parent>javax.faces.component.UIComponentBase</parent>
    <description></description>
    <attributes>
        &standard_uicomponent_attributes;
        <attribute>
            <name>onexception</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Client side callback to execute after a exception with this type occured.</description>
        </attribute>
        <attribute>
            <name>update</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Components to update after a exception with this type occured.</description>
        </attribute>
        <attribute>
            <name>type</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Exception type to handle.</description>
        </attribute>
    </attributes>
    <resources>
        <resource>
            <name>jquery/jquery.js</name>
        </resource>
        <resource>
            <name>primefaces.js</name>
        </resource>
    </resources>
</component>

=== rmpestano/prime-arquillian/primefaces/src/main/resources-maven-jsf/mobile/footer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>footer</tag>
    <tagClass>org.primefaces.mobile.component.footer.FooterTag</tagClass>
	<componentClass>org.primefaces.mobile.component.footer.Footer</componentClass>
	<componentType>org.primefaces.mobile.Footer</componentType>
	<componentFamily>org.primefaces.mobile.component</componentFamily>
	<rendererType>org.primefaces.mobile.component.FooterRenderer</rendererType>
	<rendererClass>org.primefaces.mobile.component.footer.FooterRenderer</rendererClass>
	<parent>javax.faces.component.UIPanel</parent>
	<attributes>
		&standard_uicomponent_attributes;
        <attribute>
			<name>title</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
        <attribute>
			<name>fixed</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
		</attribute>
        <attribute>
            <name>swatch</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Swatch of the footer</description>
        </attribute>
        <attribute>
            <name>tapToggle</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
            <description>For fixed footers, sets whether the fixed toolbar's visibility can be toggled by tapping on the page.</description>
        </attribute>
        <attribute>
            <name>style</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Inline style of the component.</description>
        </attribute>
        <attribute>
            <name>styleClass</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Style class of the component.</description>
        </attribute>
	</attributes>
</component>

=== rmpestano/prime-arquillian/primefaces/src/main/resources-maven-jsf/ui/rowEditor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
]>
<component>
	<tag>rowEditor</tag>
	<tagClass>org.primefaces.component.roweditor.RowEditorTag</tagClass>
	<componentClass>org.primefaces.component.roweditor.RowEditor</componentClass>
	<componentType>org.primefaces.component.RowEditor</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
    <rendererType>org.primefaces.component.RowEditorRenderer</rendererType>
	<rendererClass>org.primefaces.component.roweditor.RowEditorRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
    <description>RowToggler is a helper component for datatable.</description>
	<attributes>
		&standard_uicomponent_attributes;
	</attributes>
</component>

=== rmpestano/prime-arquillian/primefaces/src/main/resources-maven-jsf/ui/spotlight.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "../misc/component.dtd" [
<!ENTITY standard_uicomponent_attributes		SYSTEM "../entities/standard_uicomponent_attributes.xml">
<!ENTITY widget_var_attribute					SYSTEM "../entities/widget_var_attribute.xml">
]>
<component>
	<tag>spotlight</tag>
	<tagClass>org.primefaces.component.spotlight.SpotlightTag</tagClass>
	<componentClass>org.primefaces.component.spotlight.Spotlight</componentClass>
	<componentType>org.primefaces.component.Spotlight</componentType>
	<componentFamily>org.primefaces.component</componentFamily>
	<rendererType>org.primefaces.component.SpotlightRenderer</rendererType>
	<rendererClass>org.primefaces.component.spotlight.SpotlightRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
    <description>Spotlight highlights a certain component on page.</description>
    <interfaces>
		<interface>
			<name>org.primefaces.component.api.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		&standard_uicomponent_attributes;
		&widget_var_attribute;
		<attribute>
			<name>target</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Component to highlight.</description>
		</attribute>
        <attribute>
			<name>animate</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
            <description>When disabled, Displays block without animation effect</description>
		</attribute>
	</attributes>
	<resources>
        <resource>
			<name>primefaces.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
        <resource>
			<name>jquery/jquery-plugins.js</name>
		</resource>
		<resource>
			<name>primefaces.js</name>
		</resource>
	</resources>
</component>
